name: CI tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Update submodules
      run: |
        git submodule init
        git submodule update
    - name: Get Cmake version
      run: |
        cmake --version
    - name: Install dependencies
      run: |
        sudo apt-get install libjansson-dev
        sudo apt-get install libhdf5-dev
        #sudo apt-get install python3-dev
        #sudo apt-get install python3-numpy-dev
        #sudo apt-get install python3-numpy
        #sudo apt-get install python3-pip
        #sudo apt-get install python3-yaml
        #sudo apt-get install python3-psycopg2
        sudo apt-get install swig3.0
        sudo apt-get install doxygen
        sudo apt-get install graphviz
    - name: Install Python dependencies
      run: |
        which python
        python --version
        pip --version
        which python3
        python3 --version
        pip3 --version
        pip3 install setuptools
        pip3 install numpy
        pip3 install PyYAML
        pip3 install psycopg2
    - name: check numpy
      run: |
        python3 -c 'import numpy as np; print(np.get_include())'
    - name: configure
      run: |
        mkdir build
        cd build
        Python3_ROOT=$(python3 -c 'import sys; print(sys.prefix)') cmake ..
        cd -
    - name: make
      run: |
        cd build
        make
        cd -
    - name: make test
      run: |
        cd build
        make test
        cd -
